" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" skip backup for temporary files (like crontab edits)
set backupskip=/tmp/*,/private/tmp/*"

set history=50	" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch	" do incremental searching

set background=dark
set backspace=indent,eol,start
set fileencodings=ucs-bom,utf-8,default,latin1
set guifont=Courier\ 10\ Pitch\ 10
set helplang=en
set ignorecase
set nomodeline
set mouse=a
set shiftwidth=4
set showmatch
set tabstop=4
set termencoding=utf-8
set window=65
set wrapmargin=1
set visualbell

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" always set autoindenting on
set autoindent		
" perforce command ro edit file
map @@ :!p4 edit %

" color map
colors elflord
