#!/usr/bin/env bash

# echo "sourcing $BASH_SOURCE"

# export my paths
[[ -f  $HOME/.myconfigs/bash/paths ]] && source $HOME/.myconfigs/bash/paths
# common aliases
[[ -f $HOME/.myconfigs/bash/alias ]] && source $HOME/.myconfigs/bash/alias

# git completion
[[ -f  $HOME/.myconfigs/bash/git-completion.bash ]] && source $HOME/.myconfigs/bash/git-completion.bash

# source specific machine profile
export KARCH="$(uname -s).$(uname -m)"
[[ -f $HOME/.myconfigs/extra/$KARCH/bash/profile ]] && source $HOME/.myconfigs/extra/$KARCH/bash/profile

# source specific hostname profile
[[ -f $HOME/.myconfigs/extra/$HOSTNAME/bash/profile ]] && source $HOME/.myconfigs/extra/$HOSTNAME/bash/profile

